### PR TITLE
Centos7 winexe

### PR DESCRIPTION
**Pull request by beardedeagle**
- Added winexe 1.1 support for centos 7. This resolves https://github.com/saltstack/salt/issues/30658

### CODE REVIEW

**Comment by dmurphy18** [comment]
@beardedeagle works great, merging.  I think the latest on each branch would have been enough, that is redhat_pkg.sls for 2015.8.10 and 2016.3.1.

Wondering if a dependency on python-impact would be a good idea, documentation says to use  python-impact also, but forgot when testing and wondering if others would too: unless there is a use case for winexe without python-impact, in which case then no need to add python-impact as a dependency.

**Comment by dmurphy18** [comment]
Thanks for the contribution, first non-SaltStack contribution to salt-pack.

**Comment by beardedeagle** [comment]
@dmurphy18: do you mean `python-impacket`? Not sure I have ever used or installed a `python-impact`.

**Comment by dmurphy18** [comment]
yes, python-impact, talks about it being needed here https://docs.saltstack.com/en/latest/topics/cloud/windows.html

but the sentence makes them sound separate items, so maybe not a good idea to have a dependency on it after all, maybe better to have winexe stand by itself.

**Comment by beardedeagle** [comment]
It's not directly a dependency of winexe itself so I would say keep them separate and let the documentation spell out what is needed.

**Pull request merged**
